### ISSUE TITLE
feat: improve performance of theme generator 

### ISSUE THREAD

**Issue by 0xMRTT** [AdwCustomizerTeam/AdwCustomizer#108]
### Feature description

It's currently slow. The original extension is faster than the in app generator.

There is two possibilities:
- Add an Adw status page with a progress bar while generating the theme (not fixing the problem just a workaround)
- Improve the performances by working on the python code

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AdwCustomizerTeam/community/blob/main/CONTRIBUTING_GUIDELINES.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/AdwCustomizerTeam/community/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment]
Maybe a dumb question, but can we use original Monet engine or more faster [C# implementation](https://github.com/albi005/MaterialColorUtilities)?

**Comment by 0xMRTT** [comment]
Need to research but with programming everything is possible 🙂. Maybe creating a binding of the C# implementation

**Comment by daudix-UFO** [comment]
[There is a tool for creating same thing but for kde plasma](https://github.com/luisbocanegra/kde-material-you-colors), maybe some code will be interesting

**Comment by 0xMRTT** [comment]
https://pypi.org/project/PyExecJS/

We can also use pyexecjs for using js in python

**Comment by daudix-UFO** [comment]
Sounds like somthing what we need

**Comment by daudix-UFO** [comment]
There is a small problem

![изображение](https://user-images.githubusercontent.com/77155297/184453658-6e5874c3-55d5-455d-a5d9-ae9ab10a373e.png)

**Comment by 0xMRTT** [comment]
And another problem:

One of cons of PyExecJS is performance. PyExecJS communicate JavaScript runtime by text and it is slow. The other cons is that it does not fully support runtime specific features.

**Comment by 0xMRTT** [comment]
Think that's better do use the C# implementation 😜

**Comment by daudix-UFO** [comment]
Also, in TWIG I have seen this project: https://gitlab.gnome.org/GNOME/gjs

**Comment by 0xMRTT** [comment]
It's the implementation of JavaScript in GNOME.

**Comment by 0xMRTT** [comment]
I think that the faster way will be C# (mono)

**Comment by AndroGR** [comment]
I think we should find a native library (C, C++, V, Rust or something similar) instead. C# is also slow when it comes in comparison to those, similar to Java.

**Comment by luisbocanegra** [comment]
Using the python implementation you just need to downscale the source image
I don't know the fastest way to do this but here is an example using [resize()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize) to proportionally resize an image:
```py
from utils.theme_utils import *
img = Image.open('/home/luis/Pictures/Wallpapers/wallhaven-436zw6.jpg')
basewidth = 64
wpercent = (basewidth/float(img.size[0]))
hsize = int((float(img.size[1])*float(wpercent)))
img = img.resize((basewidth,hsize),Image.Resampling.LANCZOS)
print(themeFromImage(img))
```
Used `LANCZOS` because according to [pillow docs](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters) it offers the best down-scaling quality, even though is the slowest I don't think if affects too much.

Now it takes from a fraction of a second to a couple of seconds at max (in my tests at least), it affects the resulting palette a bit (looking at the values, visually looks the same) but I think is a good tradeoff.
```sh
❱ python3 test2.py
{'source': 4283663955, 'schemes': {'light': <scheme.scheme.Scheme object at 0x7f1b20099900>, 'dark': <scheme.scheme.Scheme object at 0x7f1b200994e0>}, 'palettes': {'primary': <palettes.tonal_palette.TonalPalette object at 0x7f1b20b27340>, 'secondary': <palettes.tonal_palette.TonalPalette object at 0x7f1b200998d0>, 'tertiary': <palettes.tonal_palette.TonalPalette object at 0x7f1b20099870>, 'neutral': <palettes.tonal_palette.TonalPalette object at 0x7f1b20099810>, 'neutralVariant': <palettes.tonal_palette.TonalPalette object at 0x7f1b200997b0>, 'error': <palettes.tonal_palette.TonalPalette object at 0x7f1b20099750>}, 'customColors': []}
0 ✔ (570ms)
```

With the C# implementation (that I used in [kde-material-you-colors](https://github.com/luisbocanegra/kde-material-you-colors)) also uses some form of [resizing](https://github.com/albi005/MaterialColorUtilities/blob/main/Playground/Playground.Console/Program.cs#L15)

**Comment by daudix-UFO** [comment]
Interesting fact: I created 64x64 image and selected it as background, and theme generated in a few miliseconds!

**Comment by daudix-UFO** [comment]
I think this is more than expected, closing
